# CMake generated Testfile for 
# Source directory: /Users/limmerkate/dealii-sak/tests
# Build directory: /Users/limmerkate/dealii-sak/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests/error_handler_01.debug "/opt/local/bin/cmake" "-DTRGT=error_handler_01.debug.diff" "-DTEST=tests/error_handler_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/error_handler_01.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/error_handler_01.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/error_handler_01.debug")
add_test(tests/parameter_acceptor_01.debug "/opt/local/bin/cmake" "-DTRGT=parameter_acceptor_01.debug.diff" "-DTEST=tests/parameter_acceptor_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parameter_acceptor_01.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parameter_acceptor_01.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parameter_acceptor_01.debug")
add_test(tests/parameter_acceptor_02.debug "/opt/local/bin/cmake" "-DTRGT=parameter_acceptor_02.debug.diff" "-DTEST=tests/parameter_acceptor_02.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parameter_acceptor_02.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parameter_acceptor_02.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parameter_acceptor_02.debug")
add_test(tests/parameter_acceptor_03.debug "/opt/local/bin/cmake" "-DTRGT=parameter_acceptor_03.debug.diff" "-DTEST=tests/parameter_acceptor_03.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parameter_acceptor_03.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parameter_acceptor_03.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parameter_acceptor_03.debug")
add_test(tests/parameter_acceptor_04.debug "/opt/local/bin/cmake" "-DTRGT=parameter_acceptor_04.debug.diff" "-DTEST=tests/parameter_acceptor_04.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parameter_acceptor_04.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parameter_acceptor_04.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parameter_acceptor_04.debug")
add_test(tests/parsed_finite_element_01.debug "/opt/local/bin/cmake" "-DTRGT=parsed_finite_element_01.debug.diff" "-DTEST=tests/parsed_finite_element_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_finite_element_01.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_finite_element_01.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_finite_element_01.debug")
add_test(tests/parsed_function_01.debug "/opt/local/bin/cmake" "-DTRGT=parsed_function_01.debug.diff" "-DTEST=tests/parsed_function_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_function_01.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_function_01.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_function_01.debug")
add_test(tests/parsed_grid_generator_01.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_01.debug.diff" "-DTEST=tests/parsed_grid_generator_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_01.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_01.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_01.debug")
add_test(tests/parsed_grid_generator_02.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_02.debug.diff" "-DTEST=tests/parsed_grid_generator_02.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_02.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_02.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_02.debug")
add_test(tests/parsed_grid_generator_03.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_03.debug.diff" "-DTEST=tests/parsed_grid_generator_03.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_03.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_03.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_03.debug")
add_test(tests/parsed_grid_generator_04.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_04.debug.diff" "-DTEST=tests/parsed_grid_generator_04.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_04.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_04.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_04.debug")
add_test(tests/parsed_grid_generator_05.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_05.debug.diff" "-DTEST=tests/parsed_grid_generator_05.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_05.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_05.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_05.debug")
add_test(tests/parsed_grid_generator_06.debug "/opt/local/bin/cmake" "-DTRGT=parsed_grid_generator_06.debug.diff" "-DTEST=tests/parsed_grid_generator_06.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/Users/limmerkate/dealii-sak" "-DGUARD_FILE=/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_06.debug/interrupt_guard.cc" "-P" "/Users/limmerkate/dealii/build/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/parsed_grid_generator_06.debug PROPERTIES  LABEL "tests" TIMEOUT "600" WORKING_DIRECTORY "/Users/limmerkate/dealii-sak/tests/parsed_grid_generator_06.debug")
